### ISSUE TITLE
Neet to remove .bellerina directory 

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/cellery#1019]
**Description:**
I am getting below error while trying to build a cell image.

Hasinthas-MacBook-Pro:hellohasintha hasinthaindrajee$ cellery build hellohasintha.bal hasintha/hellohasintha:latest
✔ Creating temporary executable bal file
❌ Executing ballerina build
Failed to execute ballerina build

Cellery build command failed: error in retrieving cellery cli docker instance status, exit status 1

Hasinthas-MacBook-Pro:hellohasintha hasinthaindrajee$ 
Hasinthas-MacBook-Pro:hellohasintha hasinthaindrajee$ 
Hasinthas-MacBook-Pro:hellohasintha hasinthaindrajee$ cellery build hellohasintha.bal hasintha/hellohasintha:latest
✔ Creating temporary executable bal file
Compiling source
	hellohasintha_build.bal
error: .::hellohasintha_build.bal:37:53: incompatible types: expected '(celleryio/cellery:0.5.0:CellImage|celleryio/cellery:0.5.0:Composite)', found '(celleryio/cellery:0.5.0:Composite|error)'
❌ Executing ballerina build
Failed to execute ballerina build

Cellery build command failed: error occurred while waiting to build image, Compiling source	hellohasintha_build.balerror: .::hellohasintha_build.bal:37:53: incompatible types: expected '(celleryio/cellery:0.5.0:CellImage|celleryio/cellery:0.5.0:Composite)', found '(celleryio/cellery:0.5.0:Composite|error)'

This happens when the .ballerina directory is not removed.

Since it's not possible to find user home at installation time this needs to be done at cli level.

**Comment by MadhukaHarith92** [comment]
IMO, we should not remove the entire ~/.ballerina directory but only the files related to cellery. WDYT?

**Comment by hasinthaindrajee** [comment]
+1
