### ISSUE TITLE
Error while running Cell

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/cellery#1022]
**Description:**
I am running ballerina inside docker image. When try to run a cell , the below error is displayed

Hasinthas-MacBook-Pro:hellohasintha hasinthaindrajee$ cellery run hasintha/hellohasintha:latest
✔ Extracting cell image
Compiling source
	hellohasintha_run.bal

Generating executables
Running executables

Info: Main Instance: hellohasintha-latest-ak0h
Info: Validating dependencies
Info: Instances to be Used
------------------------------------------------------------------------------------------------------------------------
INSTANCE NAME                  CELL IMAGE                          USED INSTANCE             KIND            SHARED         
------------------------------------------------------------------------------------------------------------------------
hellohasintha-latest-ak0h      hasintha/hellohasintha:latest       To be Created             Cell            -              
------------------------------------------------------------------------------------------------------------------------
Info: Dependency Tree to be Used

No Dependencies
Warning: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery/hellohasintha.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "hellohasintha-latest-ak0h" is invalid: spec.components[0].spec.template.containers[0].ports[0].protocol: Required value
error: io.cellery.exception.BallerinaCelleryException message=Unable to apply composite yaml /home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery. Command kubectl apply -f  /home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery/hellohasintha.yaml exited with exit code 1 message: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery/hellohasintha.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "hellohasintha-latest-ak0h" is invalid: spec.components[0].spec.template.containers[0].ports[0].protocol: Required value
❌ Starting main instance 
Failed to start main instance 

Cellery run command failed: failed to run bal file, failed waiting to execute run method Compiling source	hellohasintha_run.balGenerating executablesRunning executableserror: io.cellery.exception.BallerinaCelleryException message=Unable to apply composite yaml /home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery. Command kubectl apply -f  /home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery/hellohasintha.yaml exited with exit code 1 message: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image551162478/artifacts/cellery/hellohasintha.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "hellohasintha-latest-ak0h" is invalid: spec.components[0].spec.template.containers[0].ports[0].protocol: Required value

**Comment by Mirage20** [comment]
Fixed with https://github.com/wso2/cellery-controller/pull/152
