### ISSUE TITLE
Error while deploying todo sample

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/cellery#1032]
**Description:**
Tried to execute deploy todo sample from the image in cellery hub. Could observe below errors and logs. 

Hasinthas-MacBook-Pro:6 hasinthaindrajee$ cellery run wso2cellery/todo-cell:latest-dev -n todos
⠋ Extracting cell image
Pulling image wso2cellery/todo-cell:latest-dev
⠇ Extracting cell image
Image Digest : sha256:d4e22f11648fe328417d8e26149e91d0b8b5004f4f629b0363e96190a4e877e4

✔ Pulling cell image
Saving new Image to the Local Repository
✔ Extracting cell image
⠋ Starting main instance todos---------------------true
✔ Creating temporary executable main bal file
---------------------/Users/hasinthaindrajee/.cellery/tmp/cellery-cell-image787409567/src/todo
⠧ Starting main instance todos----------------------------/home/cellery/.cellery/tmp/cellery-cell-image787409567/src/todo
----------------------------[docker exec -e CELLERY_HOME=/Users/hasinthaindrajee/work/celleryhome -e CELLERY_IMAGE_DIR=/home/cellery/.cellery/tmp/cellery-cell-image787409567 -w /home/cellery/.cellery/tmp/cellery-cell-image787409567/src/todo -u 1000 45513cfeb55448e07cb1a3e66fd17257f6c4ba6980e9e3f4f8e7fada3ea65a42 /usr/lib/ballerina/ballerina-1.0.3/bin/ballerina run todo run {"org":"wso2cellery","name":"todo-cell","ver":"latest-dev","instanceName":"todos","isRoot":true} {} false false]
Compiling source
	celleryio/todo:0.6.0

Creating balos
	target/balo/todo-2019r3-any-0.6.0.balo

Generating executables
	target/bin/todo.jar

Running executables

Info: Main Instance: todos
Info: Validating dependencies
Info: Instances to be Used
------------------------------------------------------------------------------------------------------------------------
INSTANCE NAME                  CELL IMAGE                          USED INSTANCE             KIND            SHARED         
------------------------------------------------------------------------------------------------------------------------
todos                          wso2cellery/todo-cell:latest-dev    To be Created             Cell            -              
------------------------------------------------------------------------------------------------------------------------
Info: Dependency Tree to be Used

No Dependencies
Warning: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery/todo-cell.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "todos" is invalid: [spec.components[0].spec.template.containers[0].volumeMounts[0].name: Not found: "init-sql", spec.components[0].spec.template.containers[0].volumeMounts[1].name: Not found: "data-vol", spec.components[1].spec.template.containers[0].volumeMounts[0].name: Not found: "db-credentials"]
error: io.cellery.exception.BallerinaCelleryException message=Unable to apply composite yaml /home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery. Command kubectl apply -f  /home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery/todo-cell.yaml exited with exit code 1 message: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery/todo-cell.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "todos" is invalid: [spec.components[0].spec.template.containers[0].volumeMounts[0].name: Not found: "init-sql", spec.components[0].spec.template.containers[0].volumeMounts[1].name: Not found: "data-vol", spec.components[1].spec.template.containers[0].volumeMounts[0].name: Not found: "db-credentials"]
❌ Starting main instance todos
Failed to start main instance todos

Cellery run command failed: failed to run bal file, failed waiting to execute run method Compiling source	celleryio/todo:0.6.0Creating balos	target/balo/todo-2019r3-any-0.6.0.baloGenerating executables	target/bin/todo.jarRunning executableserror: io.cellery.exception.BallerinaCelleryException message=Unable to apply composite yaml /home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery. Command kubectl apply -f  /home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery/todo-cell.yaml exited with exit code 1 message: Error from server (BadRequest): error when creating "/home/cellery/.cellery/tmp/cellery-cell-image787409567/artifacts/cellery/todo-cell.yaml": admission webhook "validating.mesh.cellery.io" denied the request: validation failed: Cell.mesh.cellery.io "todos" is invalid: [spec.components[0].spec.template.containers[0].volumeMounts[0].name: Not found: "init-sql", spec.components[0].spec.template.containers[0].volumeMounts[1].name: Not found: "data-vol", spec.components[1].spec.template.containers[0].volumeMounts[0].name: Not found: "db-credentials"]

**Comment by Mirage20** [comment]
Fixed with https://github.com/wso2/cellery-controller/pull/153
