### ISSUE TITLE
Zoom in/out buttons in Cellery Designer is not working as intended

### ISSUE THREAD

**Issue by azinneera** [wso2/cellery#1080]
**Description:**
Other than for the initial click on zoom in/out, to zoom in or out , the respective button has to be clicked twice to get the intended functionality. 

Clicking on zoom in button at first works as intended and then when zoom out is clicked, it still zooms in. The second click on the zoom out button works properly.This happens the other way around as well.

**Comment by Minoli** [comment]
Resolved with https://github.com/wso2/cellery/pull/1082/commits/5574487efe46ad6b6dda2281d753ab6a7245fa3a
