### ISSUE TITLE
Cellery logs will have to appended with the component name with respective logs

### ISSUE THREAD

**Issue by sinthuja** [wso2/cellery#54]
**Description:**
Currently cellery logs <cell-name> lists the logs from all components, this needs to be improvised adding the component name along with its respective logs. And also, users should also be able to pass the argument for component name (e.g: cellery logs <cell-name> -c <component-name>) , so that the logs related to that component is printed.

**Comment by nadundesilva** [comment]
This would be useful for Cellery Tooling as well when we show the logs from an instance started by the IDE
