### ISSUE TITLE
Change the what's next message when swtching the contexts

### ISSUE THREAD

**Issue by HasithaAthukorala** [wso2/cellery#594]
When switching the context executing 

> cellery setup -> switch

 change the what's next message according to the context.

**Comment by sinthuja** [comment]
Can you please explain in bit more detail about what you expect? Currently when I do cellery setup -> switch, I get message I see below.

```
What's next ?
======================
To create your first project, execute the command:
  $ cellery init
```

What could be the possible change you would like to have?
