### ISSUE TITLE
Do you have any plans on integrating Open Policy Agent (OPA) for security?

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/cellery#620]
**Description:**
Open Policy Agent (OPA) is becoming more popular in the microservices world to provide policy-based fine-grained authorization for services. It has a nice distributed, API driven architecture that fits nicely with CBA. This would be a good feature to have in Cellery. 

[1] https://www.openpolicyagent.org/

**Suggested Labels:**
Feature

**Comment by sinthuja** [comment]
Thanks for reporting. 

We have already embedded OPA agent with our cells, but we still didn't include that in the cellery syntax and such that users can define the policies. 

We'll include in our milestone soon, and address this.
