### ISSUE TITLE
Error configuring mysql in docker desktop

### ISSUE THREAD

**Issue by tharindulak** [wso2/cellery#797]
**Description:**

When I enable PV in cellery setup, I got an issue where we could not mount volumes for the following location.  
/var/tmp/cellery/mysql.
As I suppose this may be due to an update on docker-desktop. 

I observed the following log:

Events:
  Type     Reason       Age                    From                     Message
  ----     ------       ----                   ----                     -------
  Normal   Scheduled    2m13s                  default-scheduler        Successfully assigned cellery-system/wso2apim-with-analytics-mysql-deployment-796b8998d4-zpdcm to docker-desktop
  Warning  FailedMount  2m10s (x2 over 2m12s)  kubelet, docker-desktop  MountVolume.SetUp failed for volume "mysql-dbscripts" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  10s                    kubelet, docker-desktop  Unable to mount volumes for pod "wso2apim-with-analytics-mysql-deployment-796b8998d4-zpdcm_cellery-system(8bea0b42-e6be-11e9-a2cb-025000000001)": timeout expired waiting for volumes to attach or mount for pod "cellery-system"/"wso2apim-with-analytics-mysql-deployment-796b8998d4-zpdcm". list of unmounted volumes=[apim-rdbms-persistent-storage]. list of unattached volumes=[mysql-dbscripts apim-rdbms-persistent-storage cellerysvc-account-token-4ltc6]
  Warning  FailedMount  1s (x9 over 2m9s)      kubelet, docker-desktop  MountVolume.NewMounter initialization failed for volume "wso2apim-with-analytics-mysql-pv" : path "/var/tmp/cellery/mysql" does not exist

**OS, DB, other environment details and versions:**    
macOS 10.14.6, CLI Version: 0.4.0-SNAPSHOT

**Comment by rymonteiro** [comment]
I managed to solve the problem by adding the /var/tmp as a shared folder instead of relying on symb links /private/var/tmp wich is the default shared folder.
