### ISSUE TITLE
Cellery run should wait for jobs to be published

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2/cellery#810]
**Description:**
Currently when executing `cellery run` command, the process successfully ends after all the pods are deployed. The command should also wait for any jobs to be published.

**Affected Product Version:**
0.4.0

**Steps to reproduce:**
1. Deploy a cell which exposes to the global gateway (ex. hello-world-api)
2. Every pod excluding api-publisher pod comes to running state while api-publisher pod comes to completed state

**Comment by sinthuja** [comment]
You mean the the cell run should wait until the api-publisher comes to completed state?
