### ISSUE TITLE
Timeout waiting for: "cellery setup create local -y "

### ISSUE THREAD

**Issue by joaoemilio** [wso2/cellery#883]
**Description:**
Timeout waiting for: "cellery setup create local -y "

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Cellery 0.4

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.6

**Steps to reproduce:**
Run cellery setup create local -y 

**Related Issues:**
N/A

**Comment by joaoemilio** [comment]
<img width="898" alt="Captura de Pantalla 2019-11-10 a la(s) 12 45 26" src="https://user-images.githubusercontent.com/11098232/68546735-75984280-03b8-11ea-924f-0f4ad1ccb35e.png">

**Comment by joaoemilio** [comment]
Failed to download cellery-runtime-basic-0.4.0.tar.gz from s3 bucket cellery-runtime-installation: read tcp 192.168.0.5:51978->52.219.62.83:443: read: operation timed out

**Comment by joaoemilio** [comment]
When I tried again, it started from scratch
MacBook-Joao:~ joaoemilio$ cellery setup create local -y
Downloading cellery-runtime-basic-0.4.0.tar.gz
 225.87 KB / 1.97 GB [>__________________________]   0.01% 6.41 KB/s 2d12h50m40s

**Comment by MadhukaHarith92** [comment]
This issue has been fixed in https://github.com/wso2-cellery/sdk/pull/817 , will be available in 0.5.0 release.

**Comment by nadundesilva** [comment]
I think the timeout is also another issue @joaoemilio faced.

@MadhukaHarith92 Can we restart from the previously stopped point ? I think that would be a nice improvement.

**Comment by MadhukaHarith92** [comment]
@nadundesilva +1

**Comment by MadhukaHarith92** [comment]
This is no longer valid since cellery local setup was moved to minikube in 0.6.0. It no longer downloads an image.
