### ISSUE TITLE
Failed to setup Cellery on an existing Cluster (Docker for Mac) using "cellery setup"

### ISSUE THREAD

**Issue by joaoemilio** [wso2/cellery#884]
**Description:**
Failed to setup Cellery on an existing Cluster (Docker for Mac) using "cellery setup"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Cellery 0.4

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.6

**Steps to reproduce:**
MacBook-Joao:~ joaoemilio$ cellery setup
✔ Create
✔ Existing cluster
✔ Persistent volume
✔ No
✔ Complete
✔ Load balancer [gcp, docker for desktop]
✔ Creating cellery runtime
✔ Setting up cellery namespace
✔ Applying istio crds
✔ Creating ingress-nginx
✔ Enabling istio injection
✔ Installing istio
✔ Creating controller
⠼ Configuring mysql

Failed to deploy cellery runtime: error configuring mysql: exit status 1

**Related Issues:**

**Comment by joaoemilio** [comment]
I was able to setup by choosing different options:
Non Persistent Volumes and Basic instead of Persistent Volumes (not NFS) and Complete

**Comment by MadhukaHarith92** [comment]
Hi @joaoemilio , could you please describe the resource allocation in your docker for mac?
Ideally the minimum requirements are CPUs : 4 and Memory : 8GB.

**Comment by joaoemilio** [comment]
<img width="498" alt="Captura de Pantalla 2019-11-10 a la(s) 14 18 36" src="https://user-images.githubusercontent.com/11098232/68547829-0d9c2900-03c5-11ea-9046-a9ed2ea06496.png">

**Comment by MadhukaHarith92** [comment]
Did you give the mount location in the File sharing, i.e "/var/tmp/cellery"

**Comment by joaoemilio** [comment]
I have added the /var/tmp/cellery to my File sharing config and tried the Persistent volume again but it still fails

MacBook-Joao:~ joaoemilio$ cellery setup
✔ Create
✔ Existing cluster
✔ Persistent volume
✔ No
✔ Complete
✔ Load balancer [gcp, docker for desktop]
✔ Creating cellery runtime
✔ Setting up cellery namespace
✔ Applying istio crds
✔ Creating ingress-nginx
✔ Enabling istio injection
✔ Installing istio
✔ Creating controller
⠙ Configuring mysql

Failed to deploy cellery runtime: error configuring mysql: exit status 1

MacBook-Joao:~ joaoemilio$ 

<img width="495" alt="Captura de Pantalla 2019-11-10 a la(s) 15 52 20" src="https://user-images.githubusercontent.com/11098232/68549002-1d6e3a00-03d2-11ea-9809-a723ef8564ce.png">
