### ISSUE TITLE
[Doc Issue] The step by step to enable observability isn't reflecting current options

### ISSUE THREAD

**Issue by joaoemilio** [wso2/cellery#886]
**Description:**
This is the doc I am following:
https://github.com/wso2-cellery/sdk/blob/master/docs/cellery-observability.md

Can you please check if it needs to be updated? Not a big deal tho.

**Suggested Labels:**
doc-issue

**Suggested Assignees:**

**Affected Product Version:**
Cellery 0.4

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.6

**Steps to reproduce:**
cellery setup
> modify
> observability

**Related Issues:**

**Comment by nadundesilva** [comment]
Thank you for pointing this out @joaoemilio. We will try to update this soon.
