### ISSUE TITLE
cellery init test needs to be registered as a command in the Cellery CLI

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#901]
**Description:**
Currently, `cellery init test` is not registered as a command. It is simply part of the init command itself. This results in `cellery init test` not having auto-completions, help, etc. which are automatically provided. To get these benefits we need to register it as a new command or a sub command of the init command.

**Affected Product Version:**
0.5.0-SNAPSHOT

**Comment by azinneera** [comment]
Resolved
