### ISSUE TITLE
cellery build needs to create all artifacts inside the target directory itself

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#902]
**Description:**
Currently build artifacts and the final zip file are created in the current working directory first. This can conflict with the user's folders and affect the user's project in an adverse manner. Since we are treating `target` directory as the special directory for storing build time artifacts, we should be creating all artifacts inside it (even temporary artifacts).

**Affected Product Version:**
0.5.0-SNAPSHOT and below

**Comment by nadundesilva** [comment]
Especially since we now require a ballerina project to run tests, which contains a `src` directory in the root folder, we need to fix this. The user would be most likely to run commands from the Project root and this will cause the `src` folder to be deleted.

**Comment by nadundesilva** [comment]
PR #945 fixed this issue by creating the ZIP artifacts in a temporary folder. There are few more improvements pending.

- [ ] The zip entries should be modified to use "/" instead of OS specific path separator
- [ ] Ballerina.toml packing should be revisited as we cannot assume the place of the ballerina file always

**Comment by azinneera** [comment]
Resolved
