### ISSUE TITLE
Implement a CLI command to inspect a User's run-time

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#910]
**Description:**
As of now, to debug a user's system, we need to ask the user to perform multiple actions to get information about the run-time. This can be quite frustrating for users.

To avoid this we need implement a command which would collect all relevant information about the run-time and generate a ZIP using this information. (We can update the issue templates to request the user for this information as well to reduce the debugging cycle.)

Similar to `microk8s.inspect` (https://microk8s.io/docs/troubleshooting#inspect)

**Comment by MadhukaHarith92** [comment]
Is this different from the already available command to check the runtime status, i.e `cellery setup status`?
