### ISSUE TITLE
'cellery view' does not show composite boundary

### ISSUE THREAD

**Issue by isurulucky** [wso2/cellery#947]
**Description:**
Running the `cellery view` command for a composite does now show the composite boundary in the browser. 

**Affected Product Version:**
0.5.0

**OS, DB, other environment details and versions:**    
firefox 70.0.1

**Steps to reproduce:**
Run `cellery view` on a build composite image.

**Comment by isurulucky** [comment]
![no_composite-boundary](https://user-images.githubusercontent.com/2777052/69210310-59e32800-0b80-11ea-912d-477eaaeeeaf1.png)
![no_composite_boundar](https://user-images.githubusercontent.com/2777052/69210311-59e32800-0b80-11ea-8c65-0e3c3e56fed8.png)

**Comment by Minoli** [comment]
Fixed with https://github.com/wso2-cellery/sdk/pull/951

**Comment by nadundesilva** [comment]
Closing as per the above comment
