### ISSUE TITLE
Unable to run cellery test within Ballerina Project

### ISSUE THREAD

**Issue by nadundesilva** [wso2/cellery#948]
**Description:**
`cellery test` command cannot be executed within a ballerina project. Ideally, we should not depend on the location the command is being run.

One of the observations is that most of the test command functions happens inside a `target` directory created in the current working directory. We should be using a temporary directory for this.

```
✔ Extracting cell image
✔ Creating telepresence k8s resources


Cellery test command failed: failed to test Cell instance , error occurred while copying Ballerina.toml, open /home/nadun/Downloads/test/temp_proj/target/Ballerina.toml: no such file or directory
```

**Steps to reproduce:**
1. Go to an empty directory.
2. Run `cellery init temp`
3. Run `cellery init test temp/temp.bal`
4. Navigate to `temp_proj`
5. Run `cellery build src/temp/temp.bal nadundesilva/temp:test`
6. Run `cellery test nadundesilva/temp:test` (Should not change directory before this step)

**Comment by nuwanbando** [comment]
Cellery tests are mostly about integration testing correct ?

In that sense if my java

**Comment by nuwanbando** [comment]
Is there a sample I can see on how the tests are structured ?

**Comment by azinneera** [comment]
Resolved.
